// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Context;

namespace WebAPI.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20190105201758_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.Models.AuctionItem", b =>
                {
                    b.Property<int>("ItemNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BidCustomName")
                        .IsRequired();

                    b.Property<string>("BidCustomPhone")
                        .IsRequired();

                    b.Property<int>("BidPrice");

                    b.Property<DateTime>("BidTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemDescription")
                        .IsRequired();

                    b.Property<int>("RatingPrice");

                    b.HasKey("ItemNumber");

                    b.ToTable("AuctionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
